#!/usr/bin/env bash
# Shared helpers for the fleet (sourced by worker/supervisor/dispatch).
FLEET_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$FLEET_DIR/config.env"
# per-install overrides (gitignored; generated by ./setup.sh)
# shellcheck source=/dev/null
[ -f "$FLEET_DIR/config.local.env" ] && source "$FLEET_DIR/config.local.env"
mkdir -p "$FLEET_DIR/logs" "$FLEET_DIR/worktrees" "$STATE_DIR" "$CONTROL_DIR" "$CONTROL_DIR/cancel"
chmod 700 "$CONTROL_DIR" "$CONTROL_DIR/cancel" "$STATE_DIR" "$FLEET_DIR/logs" 2>/dev/null || true
# multi-repo registry (optional). Absent/empty/invalid file = single-repo, byte-identical to before.
: "${REPOS_FILE:=$CONTROL_DIR/repos.json}"

# Shared secret pattern for the secret-gate (worker.sh). KEEP IN SYNC with redact() in
# mission-control/lib/fleet.ts. Covers: API keys, GitHub tokens (classic+fine-grained), JWTs
# (incl. Supabase service-role — the raw JWT does NOT contain the word 'service_role'), private keys.
SECRET_RE='TIKTOK_CLIENT_SECRET|SUPABASE_SERVICE_ROLE|service_role|sk-ant-|gh[opsu]_[A-Za-z0-9]{8,}|github_pat_[A-Za-z0-9_]{20,}|eyJ[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{4,}|-----BEGIN [A-Z ]*PRIVATE KEY'
export SECRET_RE

ts(){ date '+%Y-%m-%dT%H:%M:%S%z'; }
log(){ printf '%s | %s\n' "$(date '+%H:%M:%S')" "$*"; }

# state_file <issue> [repo-id] -> per-issue state path. Primary keeps the legacy name
# state/issue-<n>.json; a secondary repo (multi-repo) namespaces to state/issue-<id>--<n>.json.
state_file(){
  if [ -n "${2:-}" ]; then printf '%s\n' "$STATE_DIR/issue-$2--$1.json"
  else printf '%s\n' "$STATE_DIR/issue-$1.json"; fi
}

# emit <issue> <state> [json-extra] -> events.jsonl + state/issue-<n>.json (telemetry).
# Multi-repo: when FLEET_REPO_ID is set (secondary repo), the state file is namespaced
# (state_file) and "repo":"<id>" is merged into the event data. Unset/empty = legacy bytes.
emit(){
  local num="$1" st="$2" now; now="$(ts)"
  local extra="${3:-}"; [ -n "$extra" ] || extra='{}'
  local rid="${FLEET_REPO_ID:-}"
  if [ -n "$rid" ]; then
    extra="$(python3 -c 'import json,sys
try: d=json.loads(sys.argv[1])
except Exception: d={}
d["repo"]=sys.argv[2]
print(json.dumps(d,ensure_ascii=False))' "$extra" "$rid" 2>/dev/null)"
    [ -n "$extra" ] || extra='{}'
  fi
  printf '{"ts":"%s","issue":%s,"state":"%s","data":%s}\n' "$now" "$num" "$st" "$extra" \
    >>"$FLEET_DIR/logs/events.jsonl"
  python3 - "$(state_file "$num" "$rid")" "$num" "$st" "$now" "$extra" >/dev/null 2>&1 <<'PY'
import json,sys
path,num,st,now,extra=sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5]
try: d=json.load(open(path))
except Exception: d={"issue":int(num),"created_at":now}
try: ex=json.loads(extra)
except Exception: ex={}
d.update(ex); d.update({"issue":int(num),"state":st,"updated_at":now})
json.dump(d,open(path,"w"),ensure_ascii=False,indent=2)
PY
  push_telemetry "$num" "$st" "$extra" 2>/dev/null &   # fail-silent live push to the dashboard
}

# json_obj key val [key val ...] -> compact JSON string (safe for emit-extra)
json_obj(){ python3 -c 'import json,sys;a=sys.argv[1:];print(json.dumps(dict(zip(a[::2],a[1::2])),ensure_ascii=False))' "$@"; }

# ── control-plane helpers ────────────────────────────────────────────────
# atomic_write <path> : write stdin atomically (tmp in the same dir + rename), 0600.
# A reader never sees a half-written file. Works identically on macOS + Linux.
atomic_write(){
  local path="$1" tmp="$1.tmp.$$.$RANDOM"
  ( umask 077; cat >"$tmp" ) || { rm -f "$tmp" 2>/dev/null; return 1; }
  mv -f "$tmp" "$path" || { rm -f "$tmp" 2>/dev/null; return 1; }
  chmod 600 "$path" 2>/dev/null || true
}

# fleet_get <key> <default> : top-level scalar from control/fleet.json (never eval).
# Missing/null/parse-error/non-scalar -> default. Bool -> true/false.
fleet_get(){
  python3 - "$CONTROL_DIR/fleet.json" "$1" "$2" 2>/dev/null <<'PY'
import json,sys
path,key,dflt=sys.argv[1],sys.argv[2],sys.argv[3]
try: v=json.load(open(path)).get(key,None)
except Exception: v=None
if v is None or isinstance(v,(dict,list)): print(dflt)
elif isinstance(v,bool): print('true' if v else 'false')
else: print(v)
PY
}

# task_model <issue> : per-task model from fleet.json tasks[issue].model (sonnet|opus).
# opus only honored if ALLOW_GLOBAL_OPUS=1; otherwise empty (fall back to classifier).
task_model(){
  python3 - "$CONTROL_DIR/fleet.json" "$1" "${ALLOW_GLOBAL_OPUS:-0}" 2>/dev/null <<'PY'
import json,sys
path,issue,allow=sys.argv[1],sys.argv[2],sys.argv[3]
try: m=json.load(open(path)).get('tasks',{}).get(str(issue),{}).get('model','')
except Exception: m=''
if m=='opus' and allow!='1': m=''
if m in ('sonnet','opus'): print(m)
PY
}

# task_field <issue> <key> : string field from fleet.json tasks[issue][key] (generic, no gating).
task_field(){
  python3 - "$CONTROL_DIR/fleet.json" "$1" "$2" 2>/dev/null <<'PY'
import json,sys
path,issue,key=sys.argv[1],sys.argv[2],sys.argv[3]
try: v=json.load(open(path)).get('tasks',{}).get(str(issue),{}).get(key,'')
except Exception: v=''
print(v if isinstance(v,str) else '')
PY
}

# route_effort <issue> -> low|medium|high|xhigh|max  (per-task > global fleet.json > config EFFORT)
route_effort(){
  local e
  e="$(task_field "$1" effort)"; [ -n "$e" ] || e="$(fleet_get effort '')"
  [ -n "$e" ] || e="${EFFORT:-medium}"
  case "$e" in low|medium|high|xhigh|max) echo "$e";; *) echo medium;; esac
}

# route_depth <issue> -> solo|orchestrate  (per-task > global fleet.json > config DEPTH)
route_depth(){
  local d
  d="$(task_field "$1" depth)"; [ -n "$d" ] || d="$(fleet_get depth '')"
  [ -n "$d" ] || d="${DEPTH:-solo}"
  case "$d" in solo|orchestrate) echo "$d";; *) echo solo;; esac
}

# ── agents registry (control/agents.json — config-driven team; see mission-control/lib/agents.ts) ──
# _agents_file -> the ACTIVE registry path: runtime control/agents.json, else the committed default
# deploy/agents.default.json (override via AGENTS_DEFAULT_FILE), else nothing (-> callers fall back).
_agents_file(){
  if [ -f "$CONTROL_DIR/agents.json" ]; then printf '%s' "$CONTROL_DIR/agents.json"
  else
    local d="${AGENTS_DEFAULT_FILE:-$FLEET_DIR/deploy/agents.default.json}"
    [ -f "$d" ] && printf '%s' "$d"
  fi
}

# agent_field <agent-id> <field> : scalar field of one agent (arrays -> comma-joined; bool -> true/false).
# Empty if no registry / not found. Never evals: file path + args passed as python argv.
agent_field(){
  local af; af="$(_agents_file)"; [ -n "$af" ] || return 0
  python3 - "$af" "$1" "$2" 2>/dev/null <<'PY'
import json,sys
af,aid,key=sys.argv[1],sys.argv[2],sys.argv[3]
try: agents=json.load(open(af)).get("agents",[])
except Exception: agents=[]
a=next((x for x in agents if x.get("id")==aid), None)
if not a: sys.exit()
v=a.get(key)
if v is None or isinstance(v,dict): sys.exit()
if isinstance(v,bool): print("true" if v else "false")
elif isinstance(v,list): print(",".join(str(x) for x in v))
else: print(v)
PY
}

# role_field <role> <field> : same, for the FIRST ENABLED agent with that role.
role_field(){
  local af; af="$(_agents_file)"; [ -n "$af" ] || return 0
  python3 - "$af" "$1" "$2" 2>/dev/null <<'PY'
import json,sys
af,role,key=sys.argv[1],sys.argv[2],sys.argv[3]
try: agents=json.load(open(af)).get("agents",[])
except Exception: agents=[]
a=next((x for x in agents if x.get("enabled") and x.get("role")==role), None)
if not a: sys.exit()
v=a.get(key)
if v is None or isinstance(v,dict): sys.exit()
if isinstance(v,bool): print("true" if v else "false")
elif isinstance(v,list): print(",".join(str(x) for x in v))
else: print(v)
PY
}

# route_role <issue> [labels-csv] -> the role that should handle this task, or EMPTY.
# Precedence: per-task role (fleet.json tasks[issue].role)
#           > label_scope match (first enabled agent whose label_scope intersects the issue labels)
#           > configured DEFAULT_ROLE (only if an enabled agent has it)
#           > empty  (no registry / no confident role -> caller keeps the current global behaviour).
route_role(){
  local issue="$1" labels="${2:-}" r af
  r="$(task_field "$issue" role)"; [ -n "$r" ] && { echo "$r"; return 0; }
  af="$(_agents_file)"; [ -n "$af" ] || return 0
  python3 - "$af" "$labels" "${DEFAULT_ROLE:-}" 2>/dev/null <<'PY'
import json,sys
af,labels_csv,default_role=sys.argv[1],sys.argv[2],sys.argv[3]
try: agents=json.load(open(af)).get("agents",[])
except Exception: agents=[]
enabled=[a for a in agents if a.get("enabled")]
labels={x.strip() for x in labels_csv.split(",") if x.strip()}
for a in enabled:                                   # 2) label_scope match
    if labels and (labels & set(a.get("label_scope",[]) or [])):
        print(a.get("role","")); sys.exit()
if default_role and any(a.get("role")==default_role for a in enabled):  # 3) configured default
    print(default_role); sys.exit()
# else: empty -> caller falls back to the current global behaviour
PY
}

# cmd_field <json-line> <key> : field from one command line as ONE python argv (never eval/field-split).
cmd_field(){
  python3 -c 'import json,sys
try: print(json.loads(sys.argv[1]).get(sys.argv[2],""))
except Exception: print("")' "$1" "$2" 2>/dev/null
}

# mc_watchdog_token -> the dashboard's internal MC_WATCHDOG_TOKEN, grepped from $MC_ENV_FILE on
# the HOST. Used by worker.sh to POST the visual-PR screenshot. This value must NEVER reach the
# sandbox container (it is not passed into run-build.sh). Empty output = token unavailable.
mc_watchdog_token(){
  [ -n "${MC_ENV_FILE:-}" ] && [ -f "$MC_ENV_FILE" ] || return 0
  sed -n 's/^MC_WATCHDOG_TOKEN=//p' "$MC_ENV_FILE" | head -n1 | tr -d "\"'" | tr -d '[:space:]'
}

# notify <message> (uses NOTIFY_CMD with $MSG in scope; empty = no-op)
notify(){ [ -n "${NOTIFY_CMD:-}" ] || return 0; MSG="$1" bash -c "$NOTIFY_CMD" >/dev/null 2>&1 || true; }

# ── multi-repo registry ($REPOS_FILE — EXTRA repos next to the primary REPO/REPO_DIR) ──
# Schema: {"rev":N,"repos":[{"id","repo","dir","name","desc","green_cmd","enabled"}]}
# The PRIMARY repo is NOT in this file. No/empty/invalid file ⇒ every helper below yields
# nothing and all callers keep today's single-repo behaviour byte-identically.

# valid_repo_id <id> -> 0 when the id matches the slug contract ^[a-z0-9][a-z0-9-]{0,31}$
valid_repo_id(){ printf '%s' "${1:-}" | grep -qE '^[a-z0-9][a-z0-9-]{0,31}$'; }

# repos_list -> one line per ENABLED valid repo: id<TAB>repo<TAB>dir<TAB>green_cmd<TAB>name
# Invalid entries (bad id, missing repo/dir, tab/newline in a field) are skipped with a
# warning on stderr — never a crash. Same argv-fed python pattern as fleet_get (no stdin pipe).
repos_list(){
  [ -f "$REPOS_FILE" ] || return 0
  python3 - "$REPOS_FILE" <<'PY'
import json,re,sys
path=sys.argv[1]
try: repos=json.load(open(path)).get("repos",[]) or []
except Exception:
    print("repos.json: unreadable/invalid JSON — ignored (single-repo mode)",file=sys.stderr)
    repos=[]
if not isinstance(repos,list): repos=[]
idre=re.compile(r'^[a-z0-9][a-z0-9-]{0,31}$')
for r in repos:
    if not isinstance(r,dict): continue
    rid=r.get("id")
    if not isinstance(rid,str) or not idre.match(rid):
        print("repos.json: invalid repo id %r — skipped"%(rid,),file=sys.stderr); continue
    repo=r.get("repo"); d=r.get("dir")
    if not isinstance(repo,str) or "/" not in repo or not isinstance(d,str) or not d:
        print("repos.json: repo %r missing/invalid repo or dir — skipped"%(rid,),file=sys.stderr); continue
    if not r.get("enabled",True): continue          # disabled = not claimable (repo_field still resolves it)
    g=r.get("green_cmd"); n=r.get("name")
    g=g if isinstance(g,str) else ""
    n=n if isinstance(n,str) and n else rid
    if any(("\t" in x) or ("\n" in x) for x in (rid,repo,d,g,n)):
        print("repos.json: repo %r has a tab/newline in a field — skipped"%(rid,),file=sys.stderr); continue
    print("%s\t%s\t%s\t%s\t%s"%(rid,repo,d,g,n))
PY
}

# repo_field <id> <field> -> that repo's scalar field from $REPOS_FILE, or empty.
# Looks at ALL entries (also disabled ones): an in-flight claimed task must still resolve.
repo_field(){
  [ -f "$REPOS_FILE" ] || return 0
  python3 - "$REPOS_FILE" "$1" "$2" 2>/dev/null <<'PY'
import json,sys
path,rid,key=sys.argv[1],sys.argv[2],sys.argv[3]
try: repos=json.load(open(path)).get("repos",[]) or []
except Exception: repos=[]
r=next((x for x in repos if isinstance(x,dict) and x.get("id")==rid), None)
if not isinstance(r,dict): sys.exit()
v=r.get(key)
if v is None or isinstance(v,(dict,list)): sys.exit()
print("true" if v is True else "false" if v is False else v)
PY
}

# Claim-string contract (handed from claim_next to worker.sh):
#   primary repo  -> bare issue number    "42"          (unchanged — legacy compat)
#   secondary repo-> "<repo-id>#<issue>"  "tapsafe#42"
# claim_issue_of <claim> -> issue number · claim_repo_of <claim> -> repo id ('' for primary)
claim_issue_of(){ printf '%s\n' "${1##*#}"; }
claim_repo_of(){ case "$1" in *#*) printf '%s\n' "${1%%#*}";; esac; }

# pick_next_in <owner/name> -> next usable LABEL_READY issue in a SECONDARY repo (no claim).
# Same filters/skip-labels as pick_next; the fleet.json priority queue stays PRIMARY-ONLY
# (its entries are plain issue ints — see docs/multi-repo.md), so secondaries use GitHub order.
pick_next_in(){
  gh issue list --repo "$1" --label "$LABEL_READY" --state open --json number,labels --limit 50 \
  | python3 -c 'import json,sys
try: items=json.load(sys.stdin)
except Exception: items=[]
for it in items:
    labs={l["name"] for l in it.get("labels",[])}
    if labs & {"agent-wip","agent-done","agent-failed","agent-cancelled"}: continue
    print(it["number"]); break'
}

# pick_next_secondary -> claim string "<id>#<n>" of the first enabled secondary repo with a
# usable ready issue (file order), or nothing. No repos.json = no output = no behaviour change.
pick_next_secondary(){
  local rid rrepo rdir rgreen rname n
  while IFS=$'\t' read -r rid rrepo rdir rgreen rname; do
    [ -n "$rid" ] || continue
    n="$(pick_next_in "$rrepo")"; [ -n "$n" ] || continue
    printf '%s#%s\n' "$rid" "$n"; return 0
  done < <(repos_list 2>/dev/null)
  return 0
}

# pick_next -> number of the next usable ready issue (without claiming).
# Respects control/fleet.json priority[] (stable sort: list position first,
# rest in GitHub order) and skips agent-cancelled.
pick_next(){
  # NOTE: gh output comes via stdin -> use 'python3 -c' (not 'python3 - <<HEREDOC',
  # because a heredoc hijacks stdin and then json.load(sys.stdin) does not see the gh output).
  # fleet.json is passed as argv.
  gh issue list --repo "$REPO" --label "$LABEL_READY" --state open --json number,labels --limit 50 \
  | python3 -c 'import json,sys
try: pr=json.load(open(sys.argv[1])).get("priority",[]) or []
except Exception: pr=[]
pos={}
for i,n in enumerate(pr):
    try: pos[int(n)]=i
    except Exception: pass
cand=[]
try: items=json.load(sys.stdin)          # gh error/empty output -> no candidates instead of crash
except Exception: items=[]
for it in items:
    labs={l["name"] for l in it.get("labels",[])}
    if labs & {"agent-wip","agent-done","agent-failed","agent-cancelled"}: continue
    cand.append(it["number"])
cand.sort(key=lambda n: pos.get(n, 10**6))   # stable: ties keep GitHub order
if cand: print(cand[0])' "$CONTROL_DIR/fleet.json"
}

# ── night shift (all additive; every entry point is guarded by NIGHT_SHIFT=on, so with the
#    flag off — or a bug in any helper — daytime claiming stays byte-identical to today) ──

# in_night_window [hour] -> 0 (true) when <hour> (default: current local hour) falls inside the
# night window. start>end wraps midnight: [NIGHT_START_HOUR,24)∪[0,NIGHT_END_HOUR); start<end is
# a plain [start,end); start==end is an EMPTY window (never true). Hour arg exists for tests.
in_night_window(){
  local h="${1:-$(date +%H)}" s="${NIGHT_START_HOUR:-23}" e="${NIGHT_END_HOUR:-7}"
  case "$h" in ''|*[!0-9]*) return 1;; esac
  case "$s" in ''|*[!0-9]*) s=23;; esac
  case "$e" in ''|*[!0-9]*) e=7;; esac
  h=$((10#$h)); s=$((10#$s)); e=$((10#$e))
  if [ "$s" -gt "$e" ]; then [ "$h" -ge "$s" ] || [ "$h" -lt "$e" ]
  elif [ "$s" -lt "$e" ]; then [ "$h" -ge "$s" ] && [ "$h" -lt "$e" ]
  else return 1
  fi
}

# night_id [hour] -> YYYY-MM-DD of the day the CURRENT night started (a 23→7 night keeps one
# counter across midnight: at 02:00 the night id is yesterday's date). Hour arg for tests.
night_id(){
  local h="${1:-$(date +%H)}" s="${NIGHT_START_HOUR:-23}" e="${NIGHT_END_HOUR:-7}"
  case "$h" in ''|*[!0-9]*) h=0;; esac
  case "$s" in ''|*[!0-9]*) s=23;; esac
  case "$e" in ''|*[!0-9]*) e=7;; esac
  h=$((10#$h)); s=$((10#$s)); e=$((10#$e))
  if [ "$s" -gt "$e" ] && [ "$h" -lt "$e" ]; then
    date -v-1d +%Y-%m-%d 2>/dev/null || date -d yesterday +%Y-%m-%d
  else
    date +%Y-%m-%d
  fi
}

# night_count [hour] -> claims so far this night (counter file state/.night-<night_id>)
night_count(){
  local c; c="$(cat "$STATE_DIR/.night-$(night_id "${1:-}")" 2>/dev/null)"
  case "$c" in ''|*[!0-9]*) c=0;; esac
  echo "$c"
}

# night_cap_reached [hour] -> 0 (true) when this night's claims >= NIGHT_MAX_PR
night_cap_reached(){
  local cap="${NIGHT_MAX_PR:-5}"
  case "$cap" in ''|*[!0-9]*) cap=5;; esac
  [ "$(night_count "${1:-}")" -ge "$cap" ]
}

# night_mark_claim [hour] — increment this night's counter (atomic, 0600)
night_mark_claim(){
  printf '%s' "$(( $(night_count "${1:-}") + 1 ))" | atomic_write "$STATE_DIR/.night-$(night_id "${1:-}")"
}

# pick_next_night -> next usable LABEL_NIGHT issue (same filters/priority rules as pick_next)
pick_next_night(){
  gh issue list --repo "$REPO" --label "$LABEL_NIGHT" --state open --json number,labels --limit 50 \
  | python3 -c 'import json,sys
try: pr=json.load(open(sys.argv[1])).get("priority",[]) or []
except Exception: pr=[]
pos={}
for i,n in enumerate(pr):
    try: pos[int(n)]=i
    except Exception: pass
cand=[]
try: items=json.load(sys.stdin)
except Exception: items=[]
for it in items:
    labs={l["name"] for l in it.get("labels",[])}
    if labs & {"agent-wip","agent-done","agent-failed","agent-cancelled"}: continue
    cand.append(it["number"])
cand.sort(key=lambda n: pos.get(n, 10**6))
if cand: print(cand[0])' "$CONTROL_DIR/fleet.json"
}

# pick_next_any -> pick_next, then the secondary repos (multi-repo; claim string "<id>#<n>"),
# plus (night shift on + in window + under cap) the night queue.
# Day (LABEL_READY) issues in the PRIMARY repo keep ABSOLUTE priority; with NIGHT_SHIFT=off
# and no repos.json this IS pick_next.
pick_next_any(){
  local n; n="$(pick_next)"
  if [ -n "$n" ]; then echo "$n"; return 0; fi
  n="$(pick_next_secondary)"
  if [ -n "$n" ]; then echo "$n"; return 0; fi
  [ "${NIGHT_SHIFT:-off}" = "on" ] || return 0
  in_night_window || return 0
  night_cap_reached && return 0
  pick_next_night
}

# claim_next -> claims (ready->wip) and echoes the CLAIM STRING, or nothing.
# Primary repo -> bare issue number (unchanged). Secondary repo (repos.json) -> "<id>#<n>".
# Order: primary day queue > secondary repos (file order) > night queue (primary-only).
# Night shift: only when the day queues are EMPTY (day issues keep absolute priority) and
# NIGHT_SHIFT=on + inside the window + under the per-night cap, also claim LABEL_NIGHT issues.
# Night claims still pass through the supervisor's normal day-cap/budget/breaker gates.
claim_next(){
  local n; n="$(pick_next)"
  if [ -n "$n" ]; then
    gh issue edit "$n" --repo "$REPO" --add-label agent-wip --remove-label "$LABEL_READY" >/dev/null 2>&1 || return 0
    emit "$n" claimed '{}'; echo "$n"; return 0
  fi
  # ── additive multi-repo path (no repos.json = no-op; any failure = "no claim") ──
  local c rid rrepo
  c="$(pick_next_secondary)"
  if [ -n "$c" ]; then
    rid="$(claim_repo_of "$c")"; n="$(claim_issue_of "$c")"
    rrepo="$(repo_field "$rid" repo)"
    [ -n "$rrepo" ] || return 0
    gh issue edit "$n" --repo "$rrepo" --add-label agent-wip --remove-label "$LABEL_READY" >/dev/null 2>&1 || return 0
    ( FLEET_REPO_ID="$rid"; emit "$n" claimed '{}' )
    echo "$c"; return 0
  fi
  # ── additive night path (any failure here = "no claim", never a broken day loop) ──
  [ "${NIGHT_SHIFT:-off}" = "on" ] || return 0
  in_night_window || return 0
  night_cap_reached && return 0
  n="$(pick_next_night)"; [ -z "$n" ] && return 0
  gh issue edit "$n" --repo "$REPO" --add-label agent-wip --remove-label "$LABEL_NIGHT" >/dev/null 2>&1 || return 0
  night_mark_claim
  emit "$n" night-claim "$(json_obj night_id "$(night_id)" night_count "$(night_count)")"
  emit "$n" claimed '{}'
  echo "$n"
}

# route_model <num> <title> <body> -> sonnet|opus
# Order: per-task override (fleet.json tasks) > global router (fleet.json/config) > haiku classifier.
# Forced opus (router=opus or per-task opus) only if ALLOW_GLOBAL_OPUS=1, otherwise fall back to auto.
route_model(){
  local forced router
  forced="$(task_model "$1")"
  if [ -n "$forced" ]; then echo "$forced"; return; fi
  router="$(fleet_get router '')"; [ -n "$router" ] || router="${ROUTER:-auto}"
  case "$router" in
    opus)   [ "${ALLOW_GLOBAL_OPUS:-0}" = "1" ] && { echo opus; return; } ;;  # otherwise: fall through to classifier
    sonnet) echo sonnet; return ;;
  esac
  local out
  out="$(claude -p "Classify the complexity of this software task for model routing. Answer with EXACTLY one word, nothing else: 'sonnet' for simple/medium (copy, docs, a single UI component, small bugfix, styling) or 'opus' for complex (multi-file refactor, data-model/DB migration, architecture, security-sensitive, broad/unclear scope).

Title: $2

Body:
$3" --model "${ROUTER_MODEL:-haiku}" 2>/dev/null | tr 'A-Z' 'a-z' | grep -oE 'sonnet|opus' | head -1)"
  echo "${out:-sonnet}"
}

# parse_verdict <agent-output> -> approve | caution | reject | unknown.
# Robust: the verdict is meant to be on line 1 (emoji ✅/⚠️/❌ or the word approve/caution/reject);
# prefer line 1, fall back to scanning the whole text; severity reject > caution > approve.
parse_verdict(){
  local first whole s
  first="$(printf '%s' "$1" | head -n1 | tr 'A-Z' 'a-z')"
  whole="$(printf '%s' "$1" | tr 'A-Z' 'a-z')"
  for s in "$first" "$whole"; do
    case "$s" in
      *❌*|*reject*)  echo reject;  return;;
      *⚠️*|*caution*) echo caution; return;;
      *✅*|*approve*) echo approve; return;;
    esac
  done
  echo unknown
}

# security_decision <verdict> <blocking(true|false)> -> pass | fail.
# reject (or unparseable 'unknown') only blocks when the agent is blocking; caution/approve always pass.
# Mirrors worker.sh exactly so the decision is unit-testable without invoking the model.
security_decision(){
  case "$1" in
    reject|unknown) [ "$2" = true ] && echo fail || echo pass ;;
    caution|approve) echo pass ;;
    *)              [ "$2" = true ] && echo fail || echo pass ;;
  esac
}

# count_today <state> -> number of events with that state today (for day-cap)
count_today(){
  python3 -c 'import sys,json
st,path=sys.argv[1],sys.argv[2]
import datetime
today=datetime.date.today().isoformat()
n=0
try:
 for l in open(path):
  try: e=json.loads(l)
  except Exception: continue
  if e.get("state")==st and str(e.get("ts","")).startswith(today): n+=1
except FileNotFoundError: pass
print(n)' "$1" "$FLEET_DIR/logs/events.jsonl"
}

# consecutive_fails -> 'failed' events since the last 'pr-open' (circuit-breaker).
# Monotonic reset: ignore events with line start-byte < control/.breaker.offset
# (breaker-reset records the events.jsonl size there), so in-flight failures
# from before the reset do not trip the breaker again.
consecutive_fails(){
  local bo; bo="$(cat "$CONTROL_DIR/.breaker.offset" 2>/dev/null || echo 0)"
  case "$bo" in ''|*[!0-9]*) bo=0;; esac
  python3 - "$FLEET_DIR/logs/events.jsonl" "$bo" <<'PY'
import sys,json
path,bo=sys.argv[1],int(sys.argv[2])
try: raw=open(path,'rb').read()
except FileNotFoundError: raw=b''
starts=[]; i=0
for line in raw.splitlines(keepends=True):
    starts.append((i,line)); i+=len(line)
n=0
for start,line in reversed(starts):
    if start < bo: break
    try: e=json.loads(line.decode('utf-8','replace'))
    except Exception: continue
    s=e.get("state")
    if s=="pr-open": break
    if s=="failed": n+=1
print(n)
PY
}

# push_telemetry <issue> <state> <extra-json> -> upsert fleet_tasks + insert fleet_events
# at the SEPARATE mission-control Supabase project. Fail-silent + timed; never blocking.
push_telemetry(){
  [ -n "${SUPABASE_MC_URL:-}" ] && [ -n "${SUPABASE_MC_WRITE_KEY:-}" ] || return 0
  local num="$1" st="$2" extra="$3"
  # fleet_tasks: only table columns from the state file (no unknown fields)
  local task; task="$(python3 -c 'import json,sys
cols=["issue","state","title","branch","model","pr_url","review_verdict","error"]
try: d=json.load(open(sys.argv[1]))
except Exception: d={}
print(json.dumps({k:d[k] for k in cols if k in d}))' "$(state_file "$num" "${FLEET_REPO_ID:-}")" 2>/dev/null)"
  [ -n "$task" ] && curl -s -m 5 -o /dev/null \
    -X POST "$SUPABASE_MC_URL/rest/v1/fleet_tasks?on_conflict=issue" \
    -H "apikey: $SUPABASE_MC_WRITE_KEY" -H "Authorization: Bearer $SUPABASE_MC_WRITE_KEY" \
    -H "Content-Type: application/json" -H "Prefer: resolution=merge-duplicates" \
    -d "$task" >/dev/null 2>&1 || true
  # fleet_events: append-only event
  local ev; ev="$(python3 -c 'import json,sys
print(json.dumps({"issue":int(sys.argv[1]),"state":sys.argv[2],"data":json.loads(sys.argv[3] or "{}")}))' "$num" "$st" "$extra" 2>/dev/null)"
  [ -n "$ev" ] && curl -s -m 5 -o /dev/null \
    -X POST "$SUPABASE_MC_URL/rest/v1/fleet_events" \
    -H "apikey: $SUPABASE_MC_WRITE_KEY" -H "Authorization: Bearer $SUPABASE_MC_WRITE_KEY" \
    -H "Content-Type: application/json" \
    -d "$ev" >/dev/null 2>&1 || true
}
