#!/usr/bin/env bash
# Shared helpers for the fleet (sourced by worker/supervisor/dispatch).
FLEET_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$FLEET_DIR/config.env"
# per-install overrides (gitignored; generated by ./setup.sh)
# shellcheck source=/dev/null
[ -f "$FLEET_DIR/config.local.env" ] && source "$FLEET_DIR/config.local.env"
mkdir -p "$FLEET_DIR/logs" "$FLEET_DIR/worktrees" "$STATE_DIR" "$CONTROL_DIR" "$CONTROL_DIR/cancel"
chmod 700 "$CONTROL_DIR" "$CONTROL_DIR/cancel" "$STATE_DIR" "$FLEET_DIR/logs" 2>/dev/null || true

# Shared secret pattern for the secret-gate (worker.sh). KEEP IN SYNC with redact() in
# mission-control/lib/fleet.ts. Covers: API keys, GitHub tokens (classic+fine-grained), JWTs
# (incl. Supabase service-role — the raw JWT does NOT contain the word 'service_role'), private keys.
SECRET_RE='TIKTOK_CLIENT_SECRET|SUPABASE_SERVICE_ROLE|service_role|sk-ant-|gh[opsu]_[A-Za-z0-9]{8,}|github_pat_[A-Za-z0-9_]{20,}|eyJ[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{4,}|-----BEGIN [A-Z ]*PRIVATE KEY'
export SECRET_RE

ts(){ date '+%Y-%m-%dT%H:%M:%S%z'; }
log(){ printf '%s | %s\n' "$(date '+%H:%M:%S')" "$*"; }

# emit <issue> <state> [json-extra] -> events.jsonl + state/issue-<n>.json (telemetry)
emit(){
  local num="$1" st="$2" now; now="$(ts)"
  local extra="${3:-}"; [ -n "$extra" ] || extra='{}'
  printf '{"ts":"%s","issue":%s,"state":"%s","data":%s}\n' "$now" "$num" "$st" "$extra" \
    >>"$FLEET_DIR/logs/events.jsonl"
  python3 - "$STATE_DIR/issue-$num.json" "$num" "$st" "$now" "$extra" >/dev/null 2>&1 <<'PY'
import json,sys
path,num,st,now,extra=sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5]
try: d=json.load(open(path))
except Exception: d={"issue":int(num),"created_at":now}
try: ex=json.loads(extra)
except Exception: ex={}
d.update(ex); d.update({"issue":int(num),"state":st,"updated_at":now})
json.dump(d,open(path,"w"),ensure_ascii=False,indent=2)
PY
  push_telemetry "$num" "$st" "$extra" 2>/dev/null &   # fail-silent live push to the dashboard
}

# json_obj key val [key val ...] -> compact JSON string (safe for emit-extra)
json_obj(){ python3 -c 'import json,sys;a=sys.argv[1:];print(json.dumps(dict(zip(a[::2],a[1::2])),ensure_ascii=False))' "$@"; }

# ── control-plane helpers ────────────────────────────────────────────────
# atomic_write <path> : write stdin atomically (tmp in the same dir + rename), 0600.
# A reader never sees a half-written file. Works identically on macOS + Linux.
atomic_write(){
  local path="$1" tmp="$1.tmp.$$.$RANDOM"
  ( umask 077; cat >"$tmp" ) || { rm -f "$tmp" 2>/dev/null; return 1; }
  mv -f "$tmp" "$path" || { rm -f "$tmp" 2>/dev/null; return 1; }
  chmod 600 "$path" 2>/dev/null || true
}

# fleet_get <key> <default> : top-level scalar from control/fleet.json (never eval).
# Missing/null/parse-error/non-scalar -> default. Bool -> true/false.
fleet_get(){
  python3 - "$CONTROL_DIR/fleet.json" "$1" "$2" 2>/dev/null <<'PY'
import json,sys
path,key,dflt=sys.argv[1],sys.argv[2],sys.argv[3]
try: v=json.load(open(path)).get(key,None)
except Exception: v=None
if v is None or isinstance(v,(dict,list)): print(dflt)
elif isinstance(v,bool): print('true' if v else 'false')
else: print(v)
PY
}

# task_model <issue> : per-task model from fleet.json tasks[issue].model (sonnet|opus).
# opus only honored if ALLOW_GLOBAL_OPUS=1; otherwise empty (fall back to classifier).
task_model(){
  python3 - "$CONTROL_DIR/fleet.json" "$1" "${ALLOW_GLOBAL_OPUS:-0}" 2>/dev/null <<'PY'
import json,sys
path,issue,allow=sys.argv[1],sys.argv[2],sys.argv[3]
try: m=json.load(open(path)).get('tasks',{}).get(str(issue),{}).get('model','')
except Exception: m=''
if m=='opus' and allow!='1': m=''
if m in ('sonnet','opus'): print(m)
PY
}

# task_field <issue> <key> : string field from fleet.json tasks[issue][key] (generic, no gating).
task_field(){
  python3 - "$CONTROL_DIR/fleet.json" "$1" "$2" 2>/dev/null <<'PY'
import json,sys
path,issue,key=sys.argv[1],sys.argv[2],sys.argv[3]
try: v=json.load(open(path)).get('tasks',{}).get(str(issue),{}).get(key,'')
except Exception: v=''
print(v if isinstance(v,str) else '')
PY
}

# route_effort <issue> -> low|medium|high|xhigh|max  (per-task > global fleet.json > config EFFORT)
route_effort(){
  local e
  e="$(task_field "$1" effort)"; [ -n "$e" ] || e="$(fleet_get effort '')"
  [ -n "$e" ] || e="${EFFORT:-medium}"
  case "$e" in low|medium|high|xhigh|max) echo "$e";; *) echo medium;; esac
}

# route_depth <issue> -> solo|orchestrate  (per-task > global fleet.json > config DEPTH)
route_depth(){
  local d
  d="$(task_field "$1" depth)"; [ -n "$d" ] || d="$(fleet_get depth '')"
  [ -n "$d" ] || d="${DEPTH:-solo}"
  case "$d" in solo|orchestrate) echo "$d";; *) echo solo;; esac
}

# ── agents registry (control/agents.json — config-driven team; see mission-control/lib/agents.ts) ──
# _agents_file -> the ACTIVE registry path: runtime control/agents.json, else the committed default
# deploy/agents.default.json (override via AGENTS_DEFAULT_FILE), else nothing (-> callers fall back).
_agents_file(){
  if [ -f "$CONTROL_DIR/agents.json" ]; then printf '%s' "$CONTROL_DIR/agents.json"
  else
    local d="${AGENTS_DEFAULT_FILE:-$FLEET_DIR/deploy/agents.default.json}"
    [ -f "$d" ] && printf '%s' "$d"
  fi
}

# agent_field <agent-id> <field> : scalar field of one agent (arrays -> comma-joined; bool -> true/false).
# Empty if no registry / not found. Never evals: file path + args passed as python argv.
agent_field(){
  local af; af="$(_agents_file)"; [ -n "$af" ] || return 0
  python3 - "$af" "$1" "$2" 2>/dev/null <<'PY'
import json,sys
af,aid,key=sys.argv[1],sys.argv[2],sys.argv[3]
try: agents=json.load(open(af)).get("agents",[])
except Exception: agents=[]
a=next((x for x in agents if x.get("id")==aid), None)
if not a: sys.exit()
v=a.get(key)
if v is None or isinstance(v,dict): sys.exit()
if isinstance(v,bool): print("true" if v else "false")
elif isinstance(v,list): print(",".join(str(x) for x in v))
else: print(v)
PY
}

# role_field <role> <field> : same, for the FIRST ENABLED agent with that role.
role_field(){
  local af; af="$(_agents_file)"; [ -n "$af" ] || return 0
  python3 - "$af" "$1" "$2" 2>/dev/null <<'PY'
import json,sys
af,role,key=sys.argv[1],sys.argv[2],sys.argv[3]
try: agents=json.load(open(af)).get("agents",[])
except Exception: agents=[]
a=next((x for x in agents if x.get("enabled") and x.get("role")==role), None)
if not a: sys.exit()
v=a.get(key)
if v is None or isinstance(v,dict): sys.exit()
if isinstance(v,bool): print("true" if v else "false")
elif isinstance(v,list): print(",".join(str(x) for x in v))
else: print(v)
PY
}

# route_role <issue> [labels-csv] -> the role that should handle this task, or EMPTY.
# Precedence: per-task role (fleet.json tasks[issue].role)
#           > label_scope match (first enabled agent whose label_scope intersects the issue labels)
#           > configured DEFAULT_ROLE (only if an enabled agent has it)
#           > empty  (no registry / no confident role -> caller keeps the current global behaviour).
route_role(){
  local issue="$1" labels="${2:-}" r af
  r="$(task_field "$issue" role)"; [ -n "$r" ] && { echo "$r"; return 0; }
  af="$(_agents_file)"; [ -n "$af" ] || return 0
  python3 - "$af" "$labels" "${DEFAULT_ROLE:-}" 2>/dev/null <<'PY'
import json,sys
af,labels_csv,default_role=sys.argv[1],sys.argv[2],sys.argv[3]
try: agents=json.load(open(af)).get("agents",[])
except Exception: agents=[]
enabled=[a for a in agents if a.get("enabled")]
labels={x.strip() for x in labels_csv.split(",") if x.strip()}
for a in enabled:                                   # 2) label_scope match
    if labels and (labels & set(a.get("label_scope",[]) or [])):
        print(a.get("role","")); sys.exit()
if default_role and any(a.get("role")==default_role for a in enabled):  # 3) configured default
    print(default_role); sys.exit()
# else: empty -> caller falls back to the current global behaviour
PY
}

# cmd_field <json-line> <key> : field from one command line as ONE python argv (never eval/field-split).
cmd_field(){
  python3 -c 'import json,sys
try: print(json.loads(sys.argv[1]).get(sys.argv[2],""))
except Exception: print("")' "$1" "$2" 2>/dev/null
}

# notify <message> (uses NOTIFY_CMD with $MSG in scope; empty = no-op)
notify(){ [ -n "${NOTIFY_CMD:-}" ] || return 0; MSG="$1" bash -c "$NOTIFY_CMD" >/dev/null 2>&1 || true; }

# pick_next -> number of the next usable ready issue (without claiming).
# Respects control/fleet.json priority[] (stable sort: list position first,
# rest in GitHub order) and skips agent-cancelled.
pick_next(){
  # NOTE: gh output comes via stdin -> use 'python3 -c' (not 'python3 - <<HEREDOC',
  # because a heredoc hijacks stdin and then json.load(sys.stdin) does not see the gh output).
  # fleet.json is passed as argv.
  gh issue list --repo "$REPO" --label "$LABEL_READY" --state open --json number,labels --limit 50 \
  | python3 -c 'import json,sys
try: pr=json.load(open(sys.argv[1])).get("priority",[]) or []
except Exception: pr=[]
pos={}
for i,n in enumerate(pr):
    try: pos[int(n)]=i
    except Exception: pass
cand=[]
try: items=json.load(sys.stdin)          # gh error/empty output -> no candidates instead of crash
except Exception: items=[]
for it in items:
    labs={l["name"] for l in it.get("labels",[])}
    if labs & {"agent-wip","agent-done","agent-failed","agent-cancelled"}: continue
    cand.append(it["number"])
cand.sort(key=lambda n: pos.get(n, 10**6))   # stable: ties keep GitHub order
if cand: print(cand[0])' "$CONTROL_DIR/fleet.json"
}

# claim_next -> claims (ready->wip) and echoes the number, or nothing
claim_next(){
  local n; n="$(pick_next)"; [ -z "$n" ] && return 0
  gh issue edit "$n" --repo "$REPO" --add-label agent-wip --remove-label "$LABEL_READY" >/dev/null 2>&1 || return 0
  emit "$n" claimed '{}'; echo "$n"
}

# route_model <num> <title> <body> -> sonnet|opus
# Order: per-task override (fleet.json tasks) > global router (fleet.json/config) > haiku classifier.
# Forced opus (router=opus or per-task opus) only if ALLOW_GLOBAL_OPUS=1, otherwise fall back to auto.
route_model(){
  local forced router
  forced="$(task_model "$1")"
  if [ -n "$forced" ]; then echo "$forced"; return; fi
  router="$(fleet_get router '')"; [ -n "$router" ] || router="${ROUTER:-auto}"
  case "$router" in
    opus)   [ "${ALLOW_GLOBAL_OPUS:-0}" = "1" ] && { echo opus; return; } ;;  # otherwise: fall through to classifier
    sonnet) echo sonnet; return ;;
  esac
  local out
  out="$(claude -p "Classify the complexity of this software task for model routing. Answer with EXACTLY one word, nothing else: 'sonnet' for simple/medium (copy, docs, a single UI component, small bugfix, styling) or 'opus' for complex (multi-file refactor, data-model/DB migration, architecture, security-sensitive, broad/unclear scope).

Title: $2

Body:
$3" --model "${ROUTER_MODEL:-haiku}" 2>/dev/null | tr 'A-Z' 'a-z' | grep -oE 'sonnet|opus' | head -1)"
  echo "${out:-sonnet}"
}

# parse_verdict <agent-output> -> approve | caution | reject | unknown.
# Robust: the verdict is meant to be on line 1 (emoji ✅/⚠️/❌ or the word approve/caution/reject);
# prefer line 1, fall back to scanning the whole text; severity reject > caution > approve.
parse_verdict(){
  local first whole s
  first="$(printf '%s' "$1" | head -n1 | tr 'A-Z' 'a-z')"
  whole="$(printf '%s' "$1" | tr 'A-Z' 'a-z')"
  for s in "$first" "$whole"; do
    case "$s" in
      *❌*|*reject*)  echo reject;  return;;
      *⚠️*|*caution*) echo caution; return;;
      *✅*|*approve*) echo approve; return;;
    esac
  done
  echo unknown
}

# security_decision <verdict> <blocking(true|false)> -> pass | fail.
# reject (or unparseable 'unknown') only blocks when the agent is blocking; caution/approve always pass.
# Mirrors worker.sh exactly so the decision is unit-testable without invoking the model.
security_decision(){
  case "$1" in
    reject|unknown) [ "$2" = true ] && echo fail || echo pass ;;
    caution|approve) echo pass ;;
    *)              [ "$2" = true ] && echo fail || echo pass ;;
  esac
}

# count_today <state> -> number of events with that state today (for day-cap)
count_today(){
  python3 -c 'import sys,json
st,path=sys.argv[1],sys.argv[2]
import datetime
today=datetime.date.today().isoformat()
n=0
try:
 for l in open(path):
  try: e=json.loads(l)
  except Exception: continue
  if e.get("state")==st and str(e.get("ts","")).startswith(today): n+=1
except FileNotFoundError: pass
print(n)' "$1" "$FLEET_DIR/logs/events.jsonl"
}

# consecutive_fails -> 'failed' events since the last 'pr-open' (circuit-breaker).
# Monotonic reset: ignore events with line start-byte < control/.breaker.offset
# (breaker-reset records the events.jsonl size there), so in-flight failures
# from before the reset do not trip the breaker again.
consecutive_fails(){
  local bo; bo="$(cat "$CONTROL_DIR/.breaker.offset" 2>/dev/null || echo 0)"
  case "$bo" in ''|*[!0-9]*) bo=0;; esac
  python3 - "$FLEET_DIR/logs/events.jsonl" "$bo" <<'PY'
import sys,json
path,bo=sys.argv[1],int(sys.argv[2])
try: raw=open(path,'rb').read()
except FileNotFoundError: raw=b''
starts=[]; i=0
for line in raw.splitlines(keepends=True):
    starts.append((i,line)); i+=len(line)
n=0
for start,line in reversed(starts):
    if start < bo: break
    try: e=json.loads(line.decode('utf-8','replace'))
    except Exception: continue
    s=e.get("state")
    if s=="pr-open": break
    if s=="failed": n+=1
print(n)
PY
}

# push_telemetry <issue> <state> <extra-json> -> upsert fleet_tasks + insert fleet_events
# at the SEPARATE mission-control Supabase project. Fail-silent + timed; never blocking.
push_telemetry(){
  [ -n "${SUPABASE_MC_URL:-}" ] && [ -n "${SUPABASE_MC_WRITE_KEY:-}" ] || return 0
  local num="$1" st="$2" extra="$3"
  # fleet_tasks: only table columns from the state file (no unknown fields)
  local task; task="$(python3 -c 'import json,sys
cols=["issue","state","title","branch","model","pr_url","review_verdict","error"]
try: d=json.load(open(sys.argv[1]))
except Exception: d={}
print(json.dumps({k:d[k] for k in cols if k in d}))' "$STATE_DIR/issue-$num.json" 2>/dev/null)"
  [ -n "$task" ] && curl -s -m 5 -o /dev/null \
    -X POST "$SUPABASE_MC_URL/rest/v1/fleet_tasks?on_conflict=issue" \
    -H "apikey: $SUPABASE_MC_WRITE_KEY" -H "Authorization: Bearer $SUPABASE_MC_WRITE_KEY" \
    -H "Content-Type: application/json" -H "Prefer: resolution=merge-duplicates" \
    -d "$task" >/dev/null 2>&1 || true
  # fleet_events: append-only event
  local ev; ev="$(python3 -c 'import json,sys
print(json.dumps({"issue":int(sys.argv[1]),"state":sys.argv[2],"data":json.loads(sys.argv[3] or "{}")}))' "$num" "$st" "$extra" 2>/dev/null)"
  [ -n "$ev" ] && curl -s -m 5 -o /dev/null \
    -X POST "$SUPABASE_MC_URL/rest/v1/fleet_events" \
    -H "apikey: $SUPABASE_MC_WRITE_KEY" -H "Authorization: Bearer $SUPABASE_MC_WRITE_KEY" \
    -H "Content-Type: application/json" \
    -d "$ev" >/dev/null 2>&1 || true
}
