#!/usr/bin/env bash
# Mission Control — one-time setup for a freshly cloned repo.
# Generates per-install config (gitignored) and the dashboard env, then installs deps.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

say(){ printf '\033[36m%s\033[0m\n' "$*"; }
warn(){ printf '\033[33m! %s\033[0m\n' "$*"; }
ok(){ printf '\033[32m✓ %s\033[0m\n' "$*"; }
ask(){ # ask <var> <prompt> <default>
  local __v __p="$2" __d="${3:-}" __in
  if [ -n "$__d" ]; then read -r -p "$__p [$__d]: " __in; else read -r -p "$__p: " __in; fi
  printf -v "$1" '%s' "${__in:-$__d}"
}

say "── Mission Control setup ───────────────────────────────"

# ── prerequisites ──
command -v node >/dev/null 2>&1 || { warn "Node.js not found — install Node 22.5+ (24+ recommended)."; }
if command -v node >/dev/null 2>&1; then
  NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
  [ "${NODE_MAJOR:-0}" -ge 22 ] || warn "Node $NODE_MAJOR detected — node:sqlite needs Node 22.5+ (24+ recommended)."
fi
command -v claude >/dev/null 2>&1 && ok "Claude Code CLI present" || warn "Claude Code CLI not found — install it and run 'claude' once to sign in."
command -v gh >/dev/null 2>&1 && ok "GitHub CLI present" || warn "GitHub CLI (gh) not found — the fleet uses it to manage issues/PRs."
command -v rg >/dev/null 2>&1 || warn "ripgrep (rg) not found — knowledge retrieval will fall back to grep."

# ── gather config ──
say ""
say "Tell me about the project the agents will build:"
ask GITHUB_REPO "GitHub repo (owner/name)" ""
ask REPO_DIR "Local clone path of that repo" "$HOME/code/$(basename "${GITHUB_REPO:-project}")"
ask PROJECT_NAME "Project name (shown to agents)" "$(basename "${GITHUB_REPO:-the project}")"
ask PROJECT_DESC "Short stack/context (optional)" ""
ask GREEN_CMD "Build/green-gate command" "npm run build"
ask VAULT_DIR "Knowledge vault path (optional, Enter to skip)" ""
say ""
read -r -s -p "Dashboard password: " MC_PW; echo
[ -n "$MC_PW" ] || { MC_PW="changeme"; warn "Empty password — using 'changeme'. Change it later in mission-control/.env.local."; }
ask GITHUB_TOKEN "Fine-grained GitHub PAT for the dashboard (Enter to fill later)" ""

# offer to clone the repo if the path doesn't exist
if [ -n "$GITHUB_REPO" ] && [ ! -d "$REPO_DIR/.git" ]; then
  read -r -p "Clone https://github.com/$GITHUB_REPO into $REPO_DIR now? [y/N]: " DOCLONE
  case "$DOCLONE" in [yY]*) git clone "https://github.com/$GITHUB_REPO" "$REPO_DIR" || warn "clone failed — clone it yourself later";; esac
fi

# ── secret ──
gen_secret(){
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 32
  elif command -v node >/dev/null 2>&1; then node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("hex"))'
  else head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}
SECRET="$(gen_secret)"

# ── write config.local.env (fleet overrides) ──
write_if_ok(){ # write_if_ok <path>  (reads heredoc from stdin)
  local p="$1"
  if [ -f "$p" ]; then read -r -p "$p exists — overwrite? [y/N]: " o; case "$o" in [yY]*) ;; *) warn "kept existing $p"; cat >/dev/null; return;; esac; fi
  cat > "$p"; ok "wrote $p"
}

write_if_ok "$ROOT/config.local.env" <<EOF
# Per-install overrides (gitignored). Generated by setup.sh — edit freely.
REPO="$GITHUB_REPO"
REPO_DIR="$REPO_DIR"
PROJECT_NAME="$PROJECT_NAME"
PROJECT_DESC="$PROJECT_DESC"
GREEN_CMD="$GREEN_CMD"
VAULT_DIR="$VAULT_DIR"
EOF

write_if_ok "$ROOT/mission-control/.env.local" <<EOF
# Dashboard env (gitignored). Generated by setup.sh.
MC_DASHBOARD_PASSWORD=$MC_PW
MC_SESSION_SECRET=$SECRET
FLEET_DIR=$ROOT
REPO_DIR=$REPO_DIR
GITHUB_REPO=$GITHUB_REPO
GITHUB_TOKEN=${GITHUB_TOKEN:-replace-me}
PROJECT_NAME=$PROJECT_NAME
PROJECT_DESC=$PROJECT_DESC
VAULT_DIR=$VAULT_DIR
ALLOW_GLOBAL_OPUS=0
EOF

# ── install dashboard deps (reproducible) ──
say ""
say "Installing dashboard dependencies…"
if [ -f "$ROOT/mission-control/package-lock.json" ]; then
  ( cd "$ROOT/mission-control" && npm ci ) && ok "deps installed (npm ci)" || warn "npm ci failed — try 'npm install' in mission-control/"
else
  ( cd "$ROOT/mission-control" && npm install ) && ok "deps installed" || warn "npm install failed"
fi

say ""
ok "Setup complete."
say "Next:"
say "  1) Sign in once:   claude   (and:  gh auth login)"
say "  2) Start the dashboard:   cd mission-control && npm run dev    → http://localhost:3000"
say "  3) Start the fleet:       ./supervisor.sh        (or ./loop.sh for 24/7)"
say "  4) Add work: create GitHub issues labelled 'agent-ready' (or use 'New task' in the UI)."
[ -z "$GITHUB_TOKEN" ] && warn "Set GITHUB_TOKEN in mission-control/.env.local so the board shows your issues/PRs."
